export default DarkTheme = {
  dark: true,
  mode: 'exact',
  roundness: 5,
  colors: {
    primary: '#512DA8',
    secondary: '#9D00B2',
    accent: '#AD3D6F',
    background: '#242424',
    backgroundIcon: '#EDEBDC',
    surface: '#FFFFFF',
    text: '#EDEBDC',
    disabled: '#6B6B6B',
    placeholder: '#C5C6D0',
    backdrop: '#FFFFFF',
    card: '#191919',
    highlight: '#4CBB17',
    border: '#4D4D4D',
    notification: '#B2560D',
    gameDetails: '#151515',
    trophyColors: {
      first: '#FFD700',
      second: '#C0C0C0',
      third: '#CD7F32',
      outlined: '#EDEBDC',
      other: '#EDEBDC',
    },
    positionColors: {
      first: '#BD8E02',
      second: '#848482',
      third: '#764604',
      outlined: '#FEEDE7',
      other: '#4D4D4D',
    },
    scoreBoardColors: {
      primary: '#333333',
      accent: '#191919',
    },
    cropleCircle: {
      primary: '#FFFB8B',
      accent: '#FFD03D',
    },
  },
  fonts: {
    title: 'Lexend',
    regular: 'OpenSans',
    medium: 'OpenSans',
    light: 'OpenSans',
    thin: 'OpenSans',
  },
  animation: {
    scale: 1,
  },
};
